### ISSUE TITLE
Version text is cut in about F1 dialog

### ISSUE THREAD

**Issue by superbonaci** [notepadqq/notepadqq#1055]
**Describe the bug**
The version text is cut and I think the Copyright one also is.

**Screenshots**
![](https://i.imgur.com/EJhVCaW.png)

**Environment (please complete the following information):**
 - OS: Arch linux
 - Installation type package notepadqq 1.4.8-6
 - Qt version 5.15.5
 - Notepadqq version [find it from the menu "? -> About Notepadqq..."]

**Comment by robertapengelly** [comment]
I think that your problem is related to your display settings as mine is just fine.

![Screenshot from 2022-08-22 11-29-30](https://user-images.githubusercontent.com/55969885/185900720-1bb98609-d691-432e-b307-d3b393e99e55.png)

Juat out curiosity what version of Arch Linux are you using?

**Comment by superbonaci** [comment]
Arch unstable. Maybe it's the theme?

**Comment by robertapengelly** [comment]
It could possibly be the theme, have you tried with other themes?  What desktop environment are you using? What theme are you using?

**Comment by robertapengelly** [comment]
Right I've tried gnome, xfce and kde plasma and with the default install and configurations the dialog text isn't cut off nor as big as what yours was.  So like I asked in my previous comment, what desktop environment are you using?  What theme are you using?  Also what font sizes are you using in your desktop environment settings?

**Comment by superbonaci** [comment]
I'm using KDE Plasma with Manjaro, but don't recall scaling anything. Tried several themes and with all happens the same.

**Comment by superbonaci** [comment]
Maybe related to `sddm`?
https://github.com/sddm/sddm/issues/1576

**Comment by robertapengelly** [comment]
It won't be an sddm issue it's related to the desktop environment itself.  The following is a screenshot of a freshly installed version of Manjaro.

![Screenshot from 2022-08-23 20-29-06](https://user-images.githubusercontent.com/55969885/186249307-5d758eb3-a06b-42b1-a494-da3766b95d94.png)

If you have different fonts/sizes then that's probably why it's cut off.  Also do a search for qt in the applications menu and if you have Qt5 Settings check the fonts/sizes in there as well.

**Comment by robertapengelly** [comment]
Installed a few QT applications and messed around with different font sizes in the system settings and clementine has issues with large fonts (granted not the same one) as it doesn't use something like a scroll view meaning the dialog is either too big to see all the text or the window is cropped to the screen height again making it impossible to see all the text.

![Screenshot from 2022-08-23 21-24-14](https://user-images.githubusercontent.com/55969885/186258683-edc14907-1e39-4338-b999-2fae3756ecb7.png)

**Comment by superbonaci** [comment]
> I doubt it's an sddm issue it's probably related to the desktop environment itself. The following is a screenshot of a freshly installed version of Manjaro.

Yeah on a Virtualbox new fresh install it also looks fine, but maybe it's related to vbox graphics driver or something which handles it better. My native install of Manjaro is quite old so guessed if could have issues with old configuration files.

Then in `Global Theme` in KDE Settings, I applied a new theme to both `Appearance Settings` and `Desktop layout`, yet the issue still persisted.

The issue was fixed setting a lower value in `Force font DPI`, I think it's `96` by default, this is `notepadqq` with `80`:

![](https://i.postimg.cc/25WdKy0t/notepadqq-fixed-dpi-80.png)

**Comment by robertapengelly** [comment]
What values have you got in KDE Settings -> Appearance -> Fonts?

**Comment by superbonaci** [comment]
> What values have you got in KDE Settings -> Appearance -> Global Theme -> Fonts? Can you send a screenshot of the window?

https://i.postimg.cc/BvGTKsgf/kde-plasma-Fonts-Manjaro.png

**Comment by robertapengelly** [comment]
Okay definitely not KDE Font issue. Have you checked if you have Qt5 Settings installed?

**Comment by robertapengelly** [comment]
Also in KDE Settings scroll down and select Display and Montitor and see what values are in there.

**Comment by superbonaci** [comment]
> Okay definitely not KDE Font issue. Have you checked if you have Qt5 Settings installed?

I had only installed `qtconfig-qt4` since `qtconfig-qt5` does not exist. However did install `qt5ct-1.5-2` which I had not installed, and says `The application is not configured properly`.

Information says `The QT_QPA_PLATFORMTHEME environment variable is not set (required value: qt5ct)`:

https://i.postimg.cc/qvsZ5pjj/qt5ct-the-application-is-not-configured-properly.png

**Comment by superbonaci** [comment]
> Also in KDE Settings scroll down and select Display and Montitor and see what values are in there.

https://i.postimg.cc/yxhvrPTW/kde-display-configuration.png

**Comment by robertapengelly** [comment]
Okay so QT configuration isn't overriding KDE Settings and your display settings look fine so I'm officially stumped.  The only things I can think of is as you said earlier maybe it's an old configuration issue or maybe your display is causing things to be scaled up (perhaps the displays DPI is causing it).  One final test you could do is download something like kubuntu boot into the live environment install notepadqq (for kubuntu its apt install) and see if you have the same issues, if you do then it's probably something related to the display, if not then it's probably a configuration issue within your Manjaro install.

**Comment by superbonaci** [comment]
Yeah that could probe it. Which should I download ubuntu or kubuntu?

**Comment by robertapengelly** [comment]
Kubuntu as that's the KDE version

**Comment by robertapengelly** [comment]
Don't use the apt version as that appears to have a fix follow the instructions on https://pastebin.com/FeiP3i7F to install an older version.

**Comment by superbonaci** [comment]
> Don't use the apt version as that appears to display fine with large fonts (text wraps), follow the instructions on https://pastebin.com/FeiP3i7F to install an older version instead as that seems to be fixed sizes.

The connection times out

**Comment by robertapengelly** [comment]
Are you talking about pastebin times out?  Never mind I'll put it here instead then

sudo su
apt install gdebi-core
 
wget -P /tmp https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-common_1.4.4-1~xenial1_all.deb
wget -P /tmp https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-gtk_1.4.4-1~xenial1_all.deb
wget -P /tmp https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq_1.4.4-1~xenial1_amd64.deb
 
gdebi -n /tmp/notepadqq-common_1.4.4-1~xenial1_all.deb
gdebi -n /tmp/notepadqq_1.4.4-1~xenial1_amd64.deb
gdebi -n /tmp/notepadqq-gtk_1.4.4-1~xenial1_all.deb

**Comment by superbonaci** [comment]
Install on kubuntu went fine.
````
sudo su
apt update
apt install gdebi-core

wget -P /tmp https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-common_1.4.4-1~xenial1_all.deb
wget -P /tmp https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq-gtk_1.4.4-1~xenial1_all.deb
wget -P /tmp https://launchpad.net/~notepadqq-team/+archive/ubuntu/notepadqq/+files/notepadqq_1.4.4-1~xenial1_amd64.deb

gdebi -n /tmp/notepadqq-common_1.4.4-1xenial1_all.deb
gdebi -n /tmp/notepadqq_1.4.4-1xenial1_amd64.deb
gdebi -n /tmp/notepadqq-gtk_1.4.4-1~xenial1_all.deb
````
Here are the same screenshots from kybuntu 22.04.1 LTS x86_64:

https://i.postimg.cc/9QQx4F5M/kubuntu-22-04-1-LTS-x86-64-Display-Configuration.png

https://i.postimg.cc/mr0V6Ycz/kubuntu-22-04-1-LTS-x86-64-Fonts.png

https://i.postimg.cc/KzBQX1L9/kubuntu-22-04-1-LTS-x86-64-notepadqq.png

https://i.postimg.cc/Zq36n1Rn/kubuntu-22-04-1-LTS-x86-64-clementine.png

System information:
````
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-43-generic (64-bit)
Graphics Platform: X11
Graphics Processor: NV134
````

qt5ct is not installed

**Comment by robertapengelly** [comment]
Given how all the screenshots look fine leads me to think that the problem is related to your Manjaro install, maybe some configuration has messed up or something has gotten corrupt or something else and it doesn't look like it's anything related to the display nor notepadqq (except that the dialog and textviews really shouldn't be fixed sizes).  You said it's an old install so maybe some old configuration setting is still hanging around, something minor when wrong while upgrading, etc.

**Comment by superbonaci** [comment]
Setting `Force font DPI` to 96 makes programs look nice also. Maybe for some reasons the default dpi is much higher than that, where it's supposed to be `96`.

Looks like this bug but it's from 2017 and it's fixed:
[Font scaling in plasma/wayland is broken; fonts are far too big](https://bugs.kde.org/show_bug.cgi?id=374978)

**Comment by robertapengelly** [comment]
> Looks like this 2017 bug: [Font scaling in plasma/wayland is broken; fonts are far too big](https://bugs.kde.org/show_bug.cgi?id=374978)

Its possible that the problem could still exist, maybe it's rare and no-one has been able to identify whats causing it.  Looking for the files the link suggests and I don't have ~/.config/kcmfonts in my Manjaro VM, have you checked if you have it? ~/.config/kdeglobals seems to be related to colors so I don't think you need to worry about that.

**Comment by superbonaci** [comment]
I have only `~/.config/kdeglobals` but not `~/.config/kcmfonts`. Maybe the bug was reintroduced with an update?

This is my Manjaro system information (unstable branch):
````
Operating System: Manjaro Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.3-2-MANJARO (64-bit)
Graphics Platform: X11
````

This is the Kubuntu system information as posted before:
````
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-43-generic (64-bit)
Graphics Platform: X11
Graphics Processor: NV134
````

I think I'll reopen the bug, but no idea if this is KDE/Plasma issue or Manjaro issue. Certainly I'm not going to make a fresh install of Manjaro, it has to be fixed upstream.

**Comment by robertapengelly** [comment]
> I think I'll reopen the bug, but no idea if this is KDE/Plasma issue or Manjaro issue. Certainly I'm not going to make a fresh install of Manjaro, it has to be fixed upstream.

The only thing I can say is maybe it has been fixed, the only problem is I can't seem to figure out how to install and test software with the Manjaro live environment (that's why I suggested Kubuntu) which is stupid cause the whole point of the live environment is test things out,

**Comment by superbonaci** [comment]
Created a new user and logged in to it and same issue, so it's not any file inside /home/ folders.

**Comment by robertapengelly** [comment]
At least that eliminates the personal configs.  Like we've already said maybe cause it's an old install something has been carried over from an old version (in regards to system configs/files) and is causing the issue.

**Comment by superbonaci** [comment]
New test with Manjaro live CD:
manjaro-kde-21.3.7-220816-linux515.iso
````
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.15.60-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
````

Then installed notepadqq:
````
[manjaro manjaro]# pacman -Sy notepadqq
:: Synchronizing package databases...
 core                                  165.3 KiB  80.9 KiB/s 00:02 [####################################] 100%
 extra                                1849.1 KiB  1103 KiB/s 00:02 [####################################] 100%
 community                               7.1 MiB  1926 KiB/s 00:04 [####################################] 100%
 multilib                              180.5 KiB   349 KiB/s 00:01 [####################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (4) hyphen-2.8.8-4  qt5-webkit-5.212.0alpha4-15  woff2-1.0.2-4  notepadqq-1.4.8-6

Total Download Size:   13.73 MiB
Total Installed Size:  52.89 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 qt5-webkit-5.212.0alpha4-15-x86_64     12.4 MiB  1526 KiB/s 00:08 [####################################] 100%
 notepadqq-1.4.8-6-x86_64             1271.1 KiB   254 KiB/s 00:05 [####################################] 100%
 woff2-1.0.2-4-x86_64                   57.3 KiB  48.0 KiB/s 00:01 [####################################] 100%
 hyphen-2.8.8-4-x86_64                  16.0 KiB  35.8 KiB/s 00:00 [####################################] 100%
 Total (4/4)                            13.7 MiB   794 KiB/s 00:18 [####################################] 100%
(4/4) checking keys in keyring                                     [####################################] 100%
(4/4) checking package integrity                                   [####################################] 100%
(4/4) loading package files                                        [####################################] 100%
(4/4) checking for file conflicts                                  [####################################] 100%
(4/4) checking available disk space                                [####################################] 100%
:: Processing package changes...
(1/4) installing hyphen                                            [####################################] 100%
(2/4) installing woff2                                             [####################################] 100%
(3/4) installing qt5-webkit                                        [####################################] 100%
Optional dependencies for qt5-webkit
    gst-plugins-good: Webm codec support [installed]
(4/4) installing notepadqq                                         [####################################] 100%
Optional dependencies for notepadqq
    mathjax2: Math rendering
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Refreshing PackageKit...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
````
The issue still persists with proprietary nvidia drivers, testing with open ones.

**Comment by robertapengelly** [comment]
How did you install it with the live cd? I keep getting errors, I'll re-download the iso maybe mine is corrupt or something.  Anyways since you managed to test it and the problem is still present and given how the problem doesn't seem present with your tests on Kubuntu I think it's a Manjaro issue not a KDE issue.

**Comment by superbonaci** [comment]
I did not install anything, I'm running the live dvd: https://download.manjaro.org/kde/21.3.7/manjaro-kde-21.3.7-220816-linux515.iso.torrent

I've updated the previous post, with Manjaro using nouveau driver the issue does not happen anymore. Looks like it's nvidia proprietary drivers related.

**Comment by robertapengelly** [comment]
> I did not install anything, I'm running the live dvd

You installed notepadqq within the live environment, when I try to do it I get key errors so I'm re-downloading the ISO.

> using nouveau driver the issue does not happen anymore

That's quite interesting, I'm not sure what Kubuntu uses by default or if it includes nvidia drivers although I suspect it does as regular ubuntu has proprietary nvidia drivers just don't know if it uses them by default.

**Comment by robertapengelly** [comment]
Looking at https://linuxconfig.org/wp-content/uploads/2019/12/02-how-to-install-the-nvidia-drivers-on-ubuntu-20-04-focal-fossa-linux.png it looks like you got to install the nvidia drivers separately so Kbuntu was probably using the nouveau open source drivers by default.

**Comment by superbonaci** [comment]
Yes, the live Kubuntu from the iso `kubuntu-22.04.1-desktop-amd64.iso` is using the open source driver, in fact you can see that in comment 22: `NV134` which is nouveau driver, while manjaro live uses nvidia as displayed in comment 26: `NVIDIA GeForce GTX 1080/PCIe/SSE2`.

To test it, I installed kubuntu in another usb drive, booted from it and installed proprietary nvidia drivers, then installed notepadqq, then reboot.
This is the information in `/usr/bin/systemsettings kcm_about-distro`:
````
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-46-generic (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
````
As you can see, it's everything the same except for the kernel which is 5.15.0-43-generic instead of 5.15.0-46-generic, but it uses the nvidia proprietary driver, with these modules:
````
nvidia_drm             65536  6
nvidia_modeset       1200128  15 nvidia_drm
nvidia              35450880  865 nvidia_uvm,nvidia_modeset
drm_kms_helper        311296  2 vmwgfx,nvidia_drm
````
And notepadqq displays perfect, except that it's the beta:

![](https://i.imgur.com/qe5Tk9p.png)

So this must be a Manjaro issue. Tried to test also with KDE Neon Developer Edition 64-bit `https://files.kde.org/neon/images/developer/20220822-1851/neon-developer-20220822-1851.iso` but after grub menu doesn't boot. Will try the User edition and see what happens.

**Comment by robertapengelly** [comment]
> So this must be a Manjaro issue.

Not necessarily as the text looks scaled up, download and install the old version like you did previously and see if it's cut off.  I think it's an issue with all distros when running the proprietary nvidia drivers.

**Comment by robertapengelly** [comment]
Done a bit more googling and found:

https://www.reddit.com/r/linuxquestions/comments/8tydmn/fontscreen_scales_differently_on_nvidia_vs_nouveau/
https://www.reddit.com/r/kde/comments/8ywniu/kde_plasma_everything_is_larger_after/

Reading through both it seems that it is related to the Monitors DPI and the suggestion is the one you've already done whickh is to force scale dpi to 96.

**Comment by superbonaci** [comment]
I've got lot more information.

-First, embedded all screenshots in previous comments.

-Second, whether `/usr/bin/systemsettings kcm_about-distro` displays in `NV134` or `NVIDIA` in section `Graphics Processor` is not a guarantee to know which kernel module is in use. It can be using nouveau or nvidia_drm drivers and display whichever, it just depends on how it's displayed. So basically you must look for the kernel module in use.

-Third, tried `neon-user-20220818-0947.iso` and get the same issue, black screen after grub so can't test.

-Forth, tried also the live iso `EndeavourOS_Artemis_neo_22_7.iso` but uses XFCE4, not KDE/Plasma. And it uses the nouveau driver, notepadqq about dialog displays fine.

-Fifth, tried `garuda-dr460nized-linux-zen-220822.iso`, which is Garuda based on Arch with KDE Plasma, and it also uses the nouveau driver. This is the info displayed:
````
Operating System: Garuda Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.2-zen1-2-zen (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
````
Installed notepadqq, and it also has the issue in about, because they have personalized the fonts and UI. So apparently the cut text can also happen with nouveau driver, depending on distro settings:
![](https://i.postimg.cc/3xjcDqdL/up-garuda-fonts.png)
![](https://i.postimg.cc/yY1PbNdT/up-garuda-notepadqq.png)

-Sixth, installed kubuntu to some usb drive and booted from it, installed notepadqq and nvidia drivers, reboot. In this case, notepadqq is displayed properly with nvidia proprietary driver and no font adjustment, so looks like ubuntu got right the DPI.

**Comment by robertapengelly** [comment]
Are you sure you weren't using nvidia graphics as my Garuda looks fine.

![Screenshot from 2022-08-25 23-17-11](https://user-images.githubusercontent.com/55969885/186778689-175cfd9a-f561-4ef3-9f69-eef2a9eeab59.png)

**Comment by robertapengelly** [comment]
Looking at everything the problem isn't necessarily isolated to notepadqq, it seems more to be a display/driver issue.  The only thing that could be done in the project is to not use fixed sizes for the textviews/dialogs but then there's only so much that can be done.

**Comment by superbonaci** [comment]
You are right, it was using the nvidia. So when shows `NV134` it must be the open source driver otherwise specifies which card it is. This is updated information after new tests:

# Booting Garuda KDE with selecting proprietary nvidia drivers at grub menu:

lspci:
````
01:00.0 VGA compatible controller: NVIDIA Corporation GP104BM [GeForce GTX 1080 Mobile] (rev a1)
Kernel driver in use: nvidia
Kernel modules: nouveau, nvidia_drm, nvidia
````

notepadqq screenshot is the same as before:
![](https://i.postimg.cc/3xjcDqdL/up-garuda-fonts.png)
![](https://i.postimg.cc/yY1PbNdT/up-garuda-notepadqq.png)
![](https://i.postimg.cc/fL1z8QFN/Garuda-proprietary-NVIDIA-Settings.png)

The info is this:
````
Operating System: Garuda Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.2-zen1-2-zen (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
````

Notice that in the Fixed width section the font text does not fit the text box, so you read `rd Font Mono 10pt`

# Booting Garuda KDE with selecting open source drivers at grub menu:
About:
````
Operating System: Garuda Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.2-zen1-2-zen (64-bit)
Graphics Platform: X11
Graphics Processor: NV134
````
lspci:
````
01:00.0 VGA compatible controller: NVIDIA Corporation GP104BM [GeForce GTX 1080 Mobile] (rev a1)
Kernel driver in use: nouveau
Kernel modules: nouveau
````
Screenshots:
![](https://i.postimg.cc/xCVwFj5n/Garuda-open-source-Display-configuration.png)
![](https://i.postimg.cc/7PmRSnFx/Garuda-open-source-Fonts.png)
![](https://i.postimg.cc/wBXfMX5Y/Garuda-open-source-notepadqq.png)
Notice that the text doesn't fit entirely in the Fonts section.

So looks like definitely it's some issue with Arch based distros and nvidia proprietary driver. Ubuntu has it set properly as far as I've tested.

**Comment by superbonaci** [comment]
You can't force nvidia proprietary drivers inside a virtual machine unless you do GPU passthrough. Nvidia Quadro cards allow to do that without any hack, not possible with GeForce. So you are unlikely to reproduce the issue unless you boot physically with nvidia card.

**Comment by robertapengelly** [comment]
I've never had an nvidia card as I've always used laptops and they've all come with intel cards that's why I'm asking you to run the tests.  As for Ubuntu test did you test with the 1.4.2 version of notepadqq or just the beta?

**Comment by superbonaci** [comment]
In kubuntu tested only the beta which is the one in repos I think. Let me try the one you provided also.

**Comment by superbonaci** [comment]
Tested with kubuntu using nvidia proprietary driver, and the v2.0.0-beta+git looks good while the older one you provided v1.4.2 has the text cut. Also the Sarli text is put into another line while in the other is cut. This is without touching anything else.
![](https://i.postimg.cc/23prdp6K/notepadqq-kubuntu-nvidia-beta.png)
![](https://i.postimg.cc/DfRXp84t/notepadqq-kubuntu-nvidia.png)
So looks like you changed some configuration in the program. I wonder now if it's a problem of KDE/plasma, the nvidia proprietary driver, or each developer to fix this.

**Comment by robertapengelly** [comment]
I'm not a maintainer of this project, I've just started responding to the issues as I haven't seen any interaction from the actual devs since about 2019.  As for the different versions I think the older one has a fixed size whereas the beta doesn't hence the UI differences.  The issue may not be isolated to KDE either but may just be with the nvidia drivers (whether it's reporting the correct dpi of the display or maybe it's a bug I don't know), the main reason I've suggested KDE based distros is because you were using KDE in the first place.  You could test other desktop environments out and see if the problem is present on them but that's up to you as it's really time consuming.  The main thing to take away from all this though is that it's not a notepadqq issue (other than the fixed sizes) but is a display/settings/driver issue, well I say issue but maybe it's correct based on the displays dpi.

**Comment by superbonaci** [comment]
The issue has been reported to KDE Bugtracking System:
https://bugs.kde.org/show_bug.cgi?id=458321

**Comment by robertapengelly** [comment]
Did you file that report?  Both say "notepadqq with nouveau" but the first is normal and the second is cut off which implies they are the two different drivers.  Also like I said yesterday I think there's very little (maybe even nothing) the distro maintainers and KDE maintainers can do about and you may have to take the issue up with nvidia instead (hence the proprietary).

**Comment by robertapengelly** [comment]
Have you got the NVIDIA Settings on your Manjaro installation?  If you have look through the menus and see if it has a dpi/ppi value.  If it does send a screenshot of the window.

**Comment by superbonaci** [comment]
Yes I have reported that issue. Also added the xrandr output.
I've found a great tutorial which will try when I've got some free time:
- [Fixing DPI (Dots Per Inch) / Large Fonts](https://www.kali.org/docs/general-use/fixing-dpi/)

Also there's a whole bunch of information about Nvidia itself here:
- [Index of /XFree86](https://download.nvidia.com/XFree86/)
- [Index of /XFree86/Linux-x86_64](https://download.nvidia.com/XFree86/Linux-x86_64/)
- Check latest nvidia driver version: https://download.nvidia.com/XFree86/Linux-x86_64/latest.txt
- https://download.nvidia.com/XFree86/Linux-x86_64/515.65.01/README/ and dpi section: https://download.nvidia.com/XFree86/Linux-x86_64/515.65.01/README/dpi.html

**Comment by robertapengelly** [comment]
> Apparently it's up to end user to configure the whole thing, it's not done "automatically"

Actually that's not necessarily true as on the last page it does say:
If the display device provides an EDID, and the EDID contains information about the physical size of the display device, that is used to compute the DPI, along with the size in pixels of the first mode to be used on the display device.

Based on my calculations from your xrandr output, your screen dpi should be about 128 x 129 dots per inch.  As I don't have an nvidia card I don't know what information it reports in the NVIDIA Settings but look through it (if you have it) and see if there's anything related to DPI and see if the values are somewhat similar.

**Comment by robertapengelly** [comment]
Re-installed Manjaro and changed the DPI to 128 (which I calculated your screen as) and here's the screenshot:

![Screenshot from 2022-08-28 19-12-24](https://user-images.githubusercontent.com/55969885/187088616-1e0f85f2-d7be-4243-8a11-50e6fa15387b.png)

A quick comparison against your original screenshot of the window shows the cut offs look identical which would mean that the nvidia driver seems to be getting the correct values from the display and the issue (as we're calling it) should be taken to nvidia instead of the KDE developers as the drivers are proprietary so only nvidia can change anything related to them.

**Comment by superbonaci** [comment]
I see so maybe Nvidia has the proper value and KDE/nouveau are down-scaling too much. Do you say for my screen as it is it should be 128 DPI? According to resolution and screen size? It's 1920x1080 17.2" or 17.3" I think...

I wonder how could I check this on Windows 11 and compare...

**Comment by robertapengelly** [comment]
> Do you say for my screen as it is it should be 128 DPI?
Yeah.

> According to resolution and screen size? It's 1920x1080 17.2" or 17.3" I think...

Resolution/screen size is different from DPI/PPI.  You could think of it as something like using a marker compared to a pencil, you draw the same size box but the thickness is different.  I'm not entirely sure how to check it on Windows as the only results I can find is about changing the scale settings.

**Comment by superbonaci** [comment]
The `NVIDIA X Server Settings` command `/usr/bin/nvidia-settings` does not have any DPI/PPI setting. Only change the rotation and reflection, image quality and performance settings. It says `Resolution: 128x130 dots per inch`.

It must be KDE/Plasma thing because can't recall such issue on Gnome or XFCE4...

**Comment by superbonaci** [comment]
> Re-installed Manjaro and changed the DPI to 128 (which I calculated your screen as) and here's the screenshot:
> A quick comparison against your original screenshot of the window shows the cut offs look identical which would mean that the nvidia driver seems to be getting the correct values from the display, also like I said previously the issue (as we're calling it) should probably be taken to nvidia instead of the KDE developers as the drivers are proprietary so only nvidia can change anything related to them.

Did you try the beta 2.0 with 128 dpi? Should display ok.

**Comment by robertapengelly** [comment]
> It says Resolution: 128x130 dots per inch.

DPI is short for dots per inch so it's roughly about what I calculated (128x128).  Did you find it in Linux or Windows or both? Are they at least roughly the same?  I'll re-install Kubuntu now then change the DPI to 128 and install both the beta and the last stable build like you did and post a screenshot of both and we can see if they match up.

**Comment by superbonaci** [comment]
I only checked all of that on linux, will check with Windows later.

**Comment by robertapengelly** [comment]
> I only checked all of that on linux, will check with Windows later.

Yeah no problem.

Just finished the Kubuntu stuff here's the screenshots:

![Screenshot from 2022-08-28 21-08-34](https://user-images.githubusercontent.com/55969885/187092736-1e476c8b-22e4-4ea3-99b0-41e3901d398b.png)

![Screenshot from 2022-08-28 21-11-42](https://user-images.githubusercontent.com/55969885/187092745-49fdb32f-528d-48f7-bc93-5af6f7651f30.png)

Comparing the screenshot to the ones you provided of Kubuntu and again the cut offs look identical.  As I previously said the older version seems to have fixed sizes for things whereas the beta doesn't seem to be fixed (except the dialog itself).

**Comment by superbonaci** [comment]
Running this `PowerShell 5` script:
https://www.osdeploy.com/modules/pshot/technical/resolution-scale-and-dpi#dpi
````
Add-Type @'
using System; 
using System.Runtime.InteropServices;
using System.Drawing;

public class DPI {  
  [DllImport("gdi32.dll")]
  static extern int GetDeviceCaps(IntPtr hdc, int nIndex);

  public enum DeviceCap {
  VERTRES = 10,
  DESKTOPVERTRES = 117
  } 

  public static float scaling() {
  Graphics g = Graphics.FromHwnd(IntPtr.Zero);
  IntPtr desktop = g.GetHdc();
  int LogicalScreenHeight = GetDeviceCaps(desktop, (int)DeviceCap.VERTRES);
  int PhysicalScreenHeight = GetDeviceCaps(desktop, (int)DeviceCap.DESKTOPVERTRES);

  return (float)PhysicalScreenHeight / (float)LogicalScreenHeight;
  }
}
'@ -ReferencedAssemblies 'System.Drawing.dll' -ErrorAction Stop
Return [DPI]::scaling() * 100
````
I get a value of `100`, so according to first answer:
[Is there a way to get windows to properly display 1:1 on a low-dpi but high resolution (48" 1080p) monitor?](https://answers.microsoft.com/en-us/windows/forum/all/is-there-a-way-to-get-windows-to-properly-display/71d50329-8c21-4290-b009-a61ae589629d):
````
Smaller 100% (default) = 96
````
So my guess is my Windows 11 has `96 dpi` at `100% scaling`.

**Comment by robertapengelly** [comment]
Have you check if you have nvidia settings installed?  I think it should be in control panel if you have it

**Comment by superbonaci** [comment]
Windows or Linux?

**Comment by robertapengelly** [comment]
On Windows

**Comment by superbonaci** [comment]
Yes i have `NVIDIA Control Panel` for Windows (C:\Program Files\WindowsApps\NVIDIACorp.NVIDIAControlPanel_8.1.962.0_x64__56jybvy8sckqj\nvcplui.exe).
The settings are very similar to Linux, no specific setting for DPI.

**Comment by robertapengelly** [comment]
Ohh okay so all you'll have to go by on Windows is that powershell script you ran.

**Comment by superbonaci** [comment]
What do you mean?

**Comment by robertapengelly** [comment]
You said that the NVIDIA Control Panel doesn't contain anything related to the dots per pixel (DPI) on Windows so the powershell script output is the only thing we got to go by with regards to the DPI.
