### ISSUE TITLE
notepadqq fails to build on ArchLinux

### ISSUE THREAD

**Issue by IceflowRE** [notepadqq/notepadqq#293]
qtchooser was removed from Arch.

```
==> Beginne build()...
Info: creating stash file /tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/.qmake.stash
cd src/ui/ && ( test -e Makefile || /usr/bin/qmake-qt5 /tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui/ui.pro PREFIX=/usr -o Makefile ) && make -f Makefile 
Project MESSAGE: Release build
make[1]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui“ wird betreten
(cd "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/editor" && cd "../editor" && make DESTDIR="../../out/release/lib/../appdata/editor")
make[2]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/editor“ wird betreten
mkdir -p "../../out/release/lib/../appdata/editor"
cp -r classes styles app.js index.html init.js "../../out/release/lib/../appdata/editor"/
mkdir -p "../../out/release/lib/../appdata/editor"/libs
cp -r libs/jquery "../../out/release/lib/../appdata/editor"/libs/jquery/
# Call CodeMirror makefile passing DESTDIR as absolute path, so we have no problems with cd-ing to libs
make -C libs -f Makefile-codemirror DESTDIR="/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/out/release/appdata/editor"/libs/codemirror
make[3]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/editor/libs“ wird betreten
mkdir -p "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/out/release/appdata/editor/libs/codemirror"
cd codemirror && cp -r addon keymap lib mode theme LICENSE "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/out/release/appdata/editor/libs/codemirror"/
# Clean unnecessary files within "mode"
find "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name '*.html' -exec rm -f {} +
find "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name 'test.js' -exec rm -f {} +
cd "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/m4/ && rm -f *.txt *.sh *.in
make[3]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/editor/libs“ wird verlassen
make[2]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/editor“ wird verlassen
(cd "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/extension_tools" && cd "../extension_tools" && make DESTDIR="../../out/release/lib/../appdata/extension_tools")
make[2]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/extension_tools“ wird betreten
mkdir -p "../../out/release/lib/../appdata/extension_tools"
cp -r node_modules install.js pack.js package.json readmanifest.js "../../out/release/lib/../appdata/extension_tools"/
make[2]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/extension_tools“ wird verlassen
(cd "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui" && mkdir -p "../../out/release/lib/../bin/" && cp -f "../../support_files/launch/notepadqq" "../../out/release/lib/../bin/" && chmod 755 "../../out/release/lib/../bin/notepadqq")
(cd "/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui" && mkdir -p "../../out/release/lib/../appdata/translations" && qtchooser -run-tool=lrelease -qt=5 "../translations/notepadqq_de.ts" -qm "../../out/release/lib/../appdata/translations/notepadqq_de.qm" && qtchooser -run-tool=lrelease -qt=5 "../translations/notepadqq_hu.ts" -qm "../../out/release/lib/../appdata/translations/notepadqq_hu.qm" && qtchooser -run-tool=lrelease -qt=5 "../translations/notepadqq_pl.ts" -qm "../../out/release/lib/../appdata/translations/notepadqq_pl.qm" && qtchooser -run-tool=lrelease -qt=5 "../translations/notepadqq_ru.ts" -qm "../../out/release/lib/../appdata/translations/notepadqq_ru.qm")
/bin/sh: qtchooser: Kommando nicht gefunden.
make[1]: *** [Makefile:905: make_translations] Fehler 127
make[1]: Verzeichnis „/tmp/yaourt-tmp-iceflower/aur-notepadqq/src/notepadqq/src/ui“ wird verlassen
make: *** [Makefile:43: sub-src-ui-make_first] Fehler 2
```

/bin/sh: qtchooser: Command not found.
##

**Comment by darealshinji** [comment]
Try `make LRELEASE=lrelease` or `make LRELEASE=lrelease-qt5`.

**Comment by JuBan1** [comment]
This issue happens because the qtchooser package was recently removed from the arch extra repositories. As far as I'm aware it was supposed to be integrated into qt5-base, but it isn't at the moment.

I fixed it by replacing the call to qtchooser in ../ui/makefile with lrelease:

    make_translations:
	(lrelease "/home/s3rius/dev/qt/notepadqq/src/ui/ui.pro")

**Comment by Teklad** [comment]
qtchooser is still available in AUR, so I'm not sure whether this belongs as a notepadqq issue or would be directly related to Arch Linux.  I'm not against dropping qtchooser, though... it doesn't exactly do a whole lot in the first place.

**Comment by realchrisolin** [comment]
FYI, installing qtchooser from AUR is not exactly as straightforward as it sounds:

```
==> Finished making: qtchooser 53-2 (Fri Nov 18 09:58:56 EST 2016)
loading packages...
resolving dependencies...
looking for conflicting packages...
:: qtchooser and qt5-base are in conflict. Remove qt5-base? [y/N] y
:: qtchooser and qt5-declarative are in conflict. Remove qt5-declarative? [y/N] y
:: qtchooser and qt5-tools are in conflict. Remove qt5-tools? [y/N] y
:: qtchooser and qt5-xmlpatterns are in conflict. Remove qt5-xmlpatterns? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: libaccounts-qt: removing qt5-base breaks dependency 'qt5-base'
:: poppler-qt5: removing qt5-base breaks dependency 'qt5-base'
:: qt5-location: removing qt5-declarative breaks dependency 'qt5-declarative'
:: qt5-script: removing qt5-base breaks dependency 'qt5-base'
:: qt5-sensors: removing qt5-base breaks dependency 'qt5-base'
:: qt5-svg: removing qt5-base breaks dependency 'qt5-base'
:: qt5-webchannel: removing qt5-declarative breaks dependency 'qt5-declarative'
:: signond: removing qt5-base breaks dependency 'qt5-base'
:: transmission-qt: removing qt5-base breaks dependency 'qt5-base'
```

**Comment by realchrisolin** [comment]
Furthermore, using pacman -Rdd to get past the dependency errors so qtchooser will install not only break those dependencies, but qtchooser still isn't available afterwards.

:: Processing package changes...
```
(1/1) installing qtchooser                                                                                                                     [########################################################################################] 100%
------------------------------------------------------------
~ » transmission-qt
transmission-qt: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
------------------------------------------------------------
~ » qtchooser
zsh: command not found: qtchooser
```

**Comment by realchrisolin** [comment]
Submitted PR https://github.com/notepadqq/notepadqq/pull/325, which works around this issue.

**Comment by danieleds** [comment]
Bypass the error by using the above suggestion:

> Try `make LRELEASE=lrelease` or `make LRELEASE=lrelease-qt5`.
