### ISSUE TITLE
Notepadqq does not start

### ISSUE THREAD

**Issue by AxelMKlein** [notepadqq/notepadqq#806]
**Describe the bug**

Notepadqq does not start.

- System: Ubuntu 18.10

- Started with: notepadqq
- Notepadqq does not start, but gives the following 

**To Reproduce**
1. Install notepadqq with: sudo snap install --classic notepadqq
2. Start Notepadqq with: notepadqq
3. See error: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl".
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.
Reinstalling the application may fix this problem.
Abgebrochen (Speicherabzug geschrieben)

**Expected behavior**
Notepadqq starts.

**Screenshots**
![bildschirmfoto von 2018-11-25 17-21-20](https://user-images.githubusercontent.com/27835742/48981583-9d26ca00-f0d7-11e8-8263-c208feb1b0b3.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.10
 - Installation type [sudo snap install --classic notepadqq]
 - Qt version [find it from the menu "? -> About Qt..."]
 - Notepadqq version [notepadqq             1.4.8           855   stable     danieleds     -]

**Additional context**

**Comment by mashsajid** [comment]
Try apt-get install libxext-dev
It can solve your problem.

**Comment by JuBan1** [comment]
Are you using Wayland?

If you don't know, you should be able type `echo $XDG_SESSION_TYPE` and/or `echo $WAYLAND_DISPLAY` to find it out.

I don't know if Nqq actually works normally on Wayland. It's still something of an undiscovered country.

**Comment by Teklad** [comment]
@JuBan1 it definitely works on Wayland.... as I fixed a no-icon issue for it not long ago.  The issue here appears to be another one to add to the snap container issues.

**Comment by AxelMKlein** [comment]
@JuBan1: Usually I use Wayland. That's where I experienced the issue first. This morning I tried to start Notepadqq in an X11-session. Also there it gave the same bad result.

I also removed and re-installed Notepadqq. Still the same issue, not starting with the same messages.

**Comment by AxelMKlein** [comment]
I see the same issue on my laptop, also Ubuntu 18.10.

**Comment by AxelMKlein** [comment]
> @JuBan1: Usually I use Wayland. That's where I experienced the issue first. This morning I tried to start Notepadqq in an X11-session. Also there it gave the same bad result.
> 
> I also removed and re-installed Notepadqq. Still the same issue, not starting with the same messages.

I take it back that Notepadqq also does not start in a X11-session. In an X11-session Notepadqq starts up and works normally. So the bad behavior is limited to Wayland.

**Comment by FMuro** [comment]
Still happening.

**Comment by IgorOhrimenko** [comment]
I have the same problem.
I used notepadqq on kubuntu 18.04. Yesterday install ubuntu-desktop and after that notepadqq is broken.
Any advice from this topic did not help.
I purge ubuntu-desktop, reboot system and after that notepadqq is work.

**Comment by nmoreaud** [comment]
Still happening for me on Ubuntu 19.04

**Comment by danieleds** [comment]
@nmoreaud are you using the snap package? If so, can you try the edge version?

**Comment by nmoreaud** [comment]
I use Snap. I have the wayland error with the default version, and a
segfault with the edge version.

Le lun. 7 oct. 2019 à 16:32, Daniel Di Sarli <notifications@github.com> a
écrit :

**Comment by cristianrat** [comment]
I have this exact issue with the snap version and also the one from the software store. Same thing...
Using ubuntu 18.04

**Comment by SylwesterBogusiak** [comment]
First i have installed ibxext-dev library as @mashsajid suggested.

`apt-get install libxext-dev` 

But that didn't help.
The problem still the same.

Then I have installed synaptic package manager.
`sudo apt install synaptic`

and then i have installed all libraries with names containing 'wayland-egl' words.

![image](https://user-images.githubusercontent.com/122264765/211276345-b3676d4d-1314-4de0-86b8-8070bca00e60.png)

But there is still some issue with notepadqq.

`sudo notepadqq`

gives these errors in terminal.

`mkdir: cannot create directory '/run/user/0': Permission denied
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Documents': No such file or directory
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Desktop': No such file or directory
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Downloads': No such file or directory
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Music': No such file or directory
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Pictures': No such file or directory
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Videos': No such file or directory
ln: failed to create symbolic link '/root/snap/notepadqq/855/snap/notepadqq/855/Templates': No such file or directory
Authorization required, but no authorization protocol specified
QXcbConnection: Could not connect to display :0
Aborted
`
What to do next. It's a problem of symbolic links as I see.
I know only this command:

`ln -s <path to the file/folder to be linked> <the path of the link to be created>
`

But can't figure out how to use it to fix notepadqq installation.
Can anybody help?
I really need Notepadqq to work with. I have used Notepad++ in Windows for years it's really multitasking tool to work work with plain text.
Thanks.

**Comment by 4r7if3x** [comment]
It works when you install it via the [PPA](https://notepadqq.com/wp/download/)

**Comment by toxicantidote** [comment]
For anyone who finds this from Google like I did.

I got the snap version running on Debian 11 by doing:
`env DISABLE_WAYLAND=1 notepadqq`

in a terminal to launch Notepadqq each time. Because the Debian snap is oooooold!

This pretty much does the same thing as #807
